# Generated by Django 4.2.4 on 2023-08-29 16:49

from django.db import migrations, models
import hynix.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction_complete",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "csv_file",
                    models.FileField(upload_to=hynix.models.user_directory_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreprocessedCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("data", models.FileField(upload_to="input_csvs/")),
            ],
        ),
        migrations.CreateModel(
            name="WLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_csv", models.FileField(upload_to="input_csvs/")),
                ("Lot_ID", models.CharField(max_length=100)),
                ("avg_value", models.FloatField(blank=True, null=True)),
                ("real", models.FloatField(blank=True, null=True)),
                ("real_input_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wsimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_csv", models.FileField(upload_to="input_csvs/")),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("avg_value", models.FloatField(blank=True, null=True)),
                (
                    "last_filled_column_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
