# Generated by Django 4.2.4 on 2023-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hynix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlifecycle',
            name='real_input_time',
            field=models.DateTimeField(),
        ),
    ]
